[build]
base = "C:\\Angular\\CheapTripAngular-dev-mini\\cheapTrip"
command = "npm run build"
publish = "dist/"
node_version = "16.x"
npm_version = "8.x"
environment = { NODE_VERSION = "16.13.2" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

